### ISSUE TITLE
AppImage missing

### ISSUE THREAD

**Issue by probonopd** [crapp/labpowerqt#6]
The README says

> Linux users have two different options to run the application. Either install a package provided by your distribution or use the AppImage to run the LabPowerQt without the need to compile the source code or install any dependencies. You can download the AppImage from the github releases tab for this project.

But there seems to be no AppImage for download on the Releases tab.

**Comment by crapp** [comment]
Hey @probonopd  I know :) I wasn't able to upload any binaries because noscript firefox plugin blocked a script github is now using for uploading. Just fixed it and deployed the AppImage with the latest release. 

Thanks again for providing us with this great software!
