### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by probonopd** [crapp/labpowerqt#7]
AppImage fails to run on `ubuntu-16.04-desktop-amd64.iso` with

```
me@host:~$ /home/me/Downloads/LabPowerQt-x86_64.AppImage 
/home/me/Downloads/LabPowerQt-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/me/Downloads/LabPowerQt-x86_64.AppImage)
```
Can you build against the stock libstdc++ that comes with trusty?

**Comment by crapp** [comment]
Thanks again, I need gcc >=4.9 to be able to compile my code. So I am using this ppa https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

Seems like I get this updated libstdc++ from this repository as well. I could try to build it with the clang version trusty ships with.

**Comment by crapp** [comment]
Could you give this binary a try please?
https://transfer.sh/eMi0M/LabPowerQt-x86_64.AppImage

**Comment by probonopd** [comment]
Works for me. Thank you @crapp

**Comment by crapp** [comment]
Thanks for testing!

**Comment by probonopd** [comment]
Thanks for providing an AppImage. Added to https://github.com/probonopd/AppImageKit/wiki/AppImages/

**Comment by teocci** [comment]
Basically, just do the following commands: Firstly, install:
```sudo apt-get install libstdc++6```
This should already be installed by default, but try it anyway. If it doesn't solve it, just do the following:
```sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade```

**Comment by probonopd** [comment]
@teocci that is exactly what we want to _avoid_. But @crapp has solved it in the meantime.
